dataset: dim_store

constraints:
  - type: completeness
    column: store_id
    level: ERROR

  - type: unique
    column: store_id
    level: ERROR

  - type: completeness_threshold
    column: store_name
    threshold: 0.99
    level: WARN

  - type: completeness_threshold
    column: region
    threshold: 0.95
    level: WARN

  - type: size_greater_than
    column: ""
    threshold: 5
    level: WARN