dataset: dim_product

constraints:
  - type: completeness
    column: product_id
    level: ERROR

  - type: unique
    column: product_id
    level: ERROR

  - type: completeness_threshold
    column: product_name
    threshold: 0.99
    level: WARN

  - type: completeness_threshold
    column: category
    threshold: 0.95
    level: WARN

  - type: size_greater_than
    column: ""
    threshold: 10
    level: WARN
